-- GENERATED BY tools/generate_pathdata.js
select( 2, ... ).PathData = {
	[ 1 ] = { -- Elwynn Forest
		-- Bhag'thera
		[ 2938 ] = string.char(81, 184, 214, 163, 81, 184, 214, 163, 81, 184, 214, 163);
		-- Princess
		[ 2940 ] = string.char(234, 209, 142, 130, 234, 209, 142, 130, 234, 209, 142, 130);
		-- Morgan the Collector
		[ 2942 ] = string.char(60, 202, 81, 184, 60, 202, 81, 184, 60, 202, 81, 184);
		-- Fedfennel
		[ 3670 ] = string.char(81, 56, 91, 79, 81, 56, 91, 79, 81, 56, 91, 79);
	};
	[ 21 ] = { -- Tirisfal Glades
		-- Ressan the Needler
		[ 1482 ] = string.char(163, 112, 143, 66, 163, 112, 143, 66, 163, 112, 143, 66);
		-- Deeb
		[ 1484 ] = string.char(40, 156, 224, 122, 40, 156, 224, 122, 40, 156, 224, 122);
		-- Sri'skulk
		[ 1485 ] = string.char(132, 171, 245, 104, 132, 171, 245, 104, 132, 171, 245, 104);
		-- Bayne
		[ 1481 ] = string.char(142, 130, 204, 140, 142, 130, 204, 140, 142, 130, 204, 140);
		-- Muad
		[ 1480 ] = string.char(20, 46, 163, 112, 20, 46, 163, 112, 20, 46, 163, 112);
	};
	[ 215 ] = { -- Mulgore
		-- The Rake
		[ 3248 ] = string.char(255, 127, 163, 112, 255, 127, 163, 112, 255, 127, 163, 112);
		-- Snagglespear
		[ 3244 ] = string.char(91, 143, 193, 181, 91, 143, 193, 181, 91, 143, 193, 181);
		-- Arnak Grimtotem
		[ 3246 ] = string.char(163, 112, 173, 199, 163, 112, 173, 199, 163, 112, 173, 199);
		-- Enforcer Emilgund
		[ 3252 ] = string.char(224, 122, 173, 71, 224, 122, 173, 71, 224, 122, 173, 71);
	};
};
