-- AUTOMATICALLY GENERATED BY <_NPCScan.Tools/Tools/RoutesToPathData.lua>!
select( 2, ... ).PathData = {
	[ 475 ] = { -- Blade's Edge Mountains
		-- Hemathion
		[ 18692 ] = "J��nM]�hO5�O5�ST��L��L��H�WFR��FR��F���J��nJ��nO5�L��L��FR��J��nI���J�s�O�o�O�o�Q�r3P�|6RT��UɅ�U��iU��iQ��J���J���I���O�o�P�|6RT��U��iJ���O�o�P�|6P�|6U��iJ���";
		-- Morcrush
		[ 18690 ] = "�r7�1���3Z��3Z��9l�=ƛ�A��C���A:��A:�>;�r7r7�3Z�=Ɵ=ƛ�A��A:�=Ɩ�A:�r7­B�Z����O�4�O�4�-���¢��¢�Ů�B�Z�O�4��¢�B�Z�������V���\"��e?��K���C���C���;~��9��>:7�\"E���G���MB�Xf��iD��k~����㎊�㎊�������\"�>:7��G���=w�㎊���\"�耰��9��>:7��=w��k~�㎊�耰��9���=w�=��k~�耰� hy��9��=��>���iD��k~� hy��C���9���>���iD� hy��e?��C���>���E�MB��iD��e?��C���E�MB��e?��C���MB";
		-- Speaker Mar'grom
		[ 18693 ] = "e���i=z�m�x�m�x�o�|o4��o4��lӑnfՕzfՕzd�e���e���m�x�o4��o4��fՕze���\\@v�\r=��u@U�u@U��K��1R �1R ��YΏ�Z��Z��W��Rѐ4L���I	�\\@v�\\@v�u@U�1R �1R ��Z�Rѐ4L��\\@v�1R �1R �Rя;P��1R �;P��4L���/���,Ө�/(��/(�@.��F\
��F\
�dF���?���?��4��/���/���/(��F\
��F\
��?���/�l�iqh��t`�4t`�4v��x��Sx��Sy���xl��xl��mB��j���j���j^��l�il�it`�4x��Sx��Sxl��j���x��Sj���l�i";
	};
	[ 486 ] = { -- Borean Tundra
		-- Fumblub Gearwind
		[ 32358 ] = "�t'L��*=�-2��-2��:e�5F�9S{�vO��JǮJǬ:e�-2��-2���C��iGռ�P��ZD�V_;�V_;�2g��]��]��UTS��J��CGy�lGl�\
D��\
D��5?�&��&��t'L�-2��-2��5F��3M�9S{�JǱ-2��-2��iGռ�P��CGy�\
D��&��&��-2���3M�9S{�-2���P���J��CGy�&��&���3M��6��Xȳ9S{��P��]���J��&��&���6��>(��Xȼ�P��V_;�]��&���>(�![d��XȼV_;�]���>(�LK6�![d�V_;�]��]��LK6��U���U��![d�]�";
		-- Icehorn
		[ 32361 ] = "�pz��4r��TobӼs��wxl�q~��$|��}��pz��pz��TobӼs�Ӽs��q~��$|Ӽs��$|�pz�ҩL��M��0S��0S��UR��9R3�9R3�VN(�S��S��YkіX�іX�˟T��oM��oM�ҩL�0S��0S��9R3�S�іX��oM��0S��0S��S�іX��Xb���cg��`���`��*`�Xb�";
		-- Old Crystalbark
		[ 32357 ] = "4Lq5SC�9�C�I�Q'N(K^Q-KX�E�V�C{U?;U?;V;0Z#?�Z#?�\\\"C�[�L[�LT`T�RTUSIrW�>^7�X�4Lq9�C�8�J�I�Q'Q-KU%O�X�E�U?;Z#?�[�LRTUSIrW�7�X�4Lq8�J�AoU�I�Q'U%O�W�M]X�E�Z#?�7�X�8�J�;#S3W�M]Z#?�[�L7�X�;#S3AoU�U%O�W�M][�LIrW�7�X�AoU�U%O�[�LIrW�AoU�U%O�IrW�";
	};
	[ 488 ] = { -- Dragonblight
		-- Crazed Indu'le Survivor
		[ 32409 ] = "&+��&�I)���,���3�Q>B��>B��@.�lD���D���K��\000U��BU��BW�� K6�@K6�@H���D{�PD{�PA���@��|2��,J��(��r(��r&+��)���,���>B��D���D���U��BK6�@K6�@D{�P@��|(��r)���,���D���K6�@@��|2��(��r,���D���@��|<��<��2��,���,���D���<��%�wR%�p�(�o�(�o�+)yk)�{/(�o�)�{/%�wR";
		-- Scarlet Highlord Daion
		[ 32417 ] = "��7ܵ�2���9��ANįF��SH��SH�/G���C@��C@��7ܸ�9���9��AN�SH��9��SH⶧C@�=m��j���`|��`|�\\`\000�f_�f_�mi���n!��n!�!oo�=m��=m���`|�f_�f_��n!�=m̶��R������߹r�w���G�������A�@�s�|Ů�|Ů�n�V�ϸQ���R��߹r�w�r�w����������A�|Ů�ϸQ�ϸQ���R�r�w�r�w����\
�O�\
�O���A�ϸQ�r�w�\
�O�ϸQ";
		-- Tukemuth
		[ 32400 ] = "�M}��H��;I��QG�qLI�vHίvHδFH��L���L��>TZ��X�brG�w���|ӵ�|Ӳ��ְo���o�����v����@�n�@�d�˞\r�˞\r�,�͖��[�Ɏ����[�,�͔,�͉����������s�Ґ�v���v���[W�M}�M}�;I��oNҧQG�vHζ�L���L���X��X�brG��|Ӱo���o������W�*�˞\r���[�������e�Ɏ��,�͔,�ͅ�����v���v��M}�oNҧQG��L���X�i]��brG�o���o���W�*�\
��@�n�˞\r�������e�,�͐�v���v��oNң`Q��`Q��QG��X�i]��o���\
��@�n���������\
�+���e��v���v��`Q���X�i]��\
���V��V�@�n�����ԃ��\
�+��v���v���X�i]���V�����\\���C���ԃ���v���v��i]���V��V�\\����*�C����v���V��V��*�C��";
	};
	[ 141 ] = { -- Dustwallow Marsh
		-- Dart
		[ 14232 ] = "t�2u)x�%�x�%�{�$3}�&�}�&�~�3T}O5�}O5�y6t�2t�2x�%�}�&�}�&�}O5�t�2";
	};
	[ 490 ] = { -- Grizzly Hills
		-- Arcturis
		[ 38453 ] = "Ni�MNB�BQ�BQ�BQʒ@Ni�M";
		-- Grocklar
		[ 32422 ] = "�u�jW*f8*f8�dz�f_!�r'y�(1�o(1�o'R�\r%S�,%S�,���Ƒa�u*f8�f_!�r(1�o%S�,%S�,Ƒa�����u�f_�f_!�r%S�,���f_%S�,Q���M\"ʲ�\"ʲ�)��71�B71�B8��:���:���9��/��*%9�lQ�\"ʲ�\"ʲ�71�B:���/��*%9�l\"ʲ�\"ʲ�:���/��*3���5S�B<ډ�<ډ�B ��D%�)D%�)DM��BT�xBT�x5��3Ö�3Ö�3���<ډ�<ډ�D%�)BT�x<ډ�BT�x3Ö�";
		-- Seething Hate
		[ 32429 ] = "C,vfDq[H�r�H�r�I#v�D�z�H�r�D�z�C,vfW$zW[]{/[=|[=|Y	��U`�[=|U`�W$zWd9y�hz�i��i��f��a���a���aN|�d9y�i��a���d9y�";
		-- Syreian the Bonecarver
		[ 32438 ] = "��W��.Rh��K���B��=w�n=�n=�T?�� D��M��CR�.Y��.Y��Z���_;�_c��g�Ĕl�Ĕl��Oq뼸pH��b���]j��Z)��V�\\q�wa��wa��kګnO�nO��kdå�a�|^��[��[���W���K���B�n=� D��.Y���_;�_c��_c�Ĕl���pH��b���Z)�:R���V�wa��nO��a�[���K���K���B� D��M��.Y��_c��_c�pH�\000j)��V�nO��dç�då�a��K���K�� D���H�M��_c�\000j)��R��V�dä�K���H�M��M��\000j)��b���R��dä�K��M���b��:R��cP;��R��K��M��:R��cP;��K��M��cP;";
	};
	[ 465 ] = { -- Hellfire Peninsula
		-- Fulgorge
		[ 18678 ] = ";�G9��f:�p:�p;���>5y	>5y	B obG�j=K�cZN}YQ:Y�Q:Y�Q�\\�P�d�P�d�N�i	Ko\\@��}@��>���>���:e��;�G;�G:�p>5y	K�cZQ:Y�P�d�P�d�Ko\\Gs@�i@��}>���>���;�G>5y	G�j=K�cZP�d�@�i>���>5y	>5y	G�j=P�d�A؃F@�i>5y	>5y	P�d�GsC�yA؃F>5y	>5y	GsC�yH���F�ZFܩ�Fܩ�J���P\000�\"X1��Z͉�]�\
]�\
a��i=Anc}�rGz0s�{�s�{�sn�Sq��8q��8j=��d��e[6��[)��X���L���H���Fܩ�Fܩ�P\000�\"U֙]�\
i=Anc}�nc}�s�{�q��8[6��X���T9��RG��L���Fܩ�]�\
nc}�q��8]I��[6��T9��RG��Fܩ�U֙]�\
q��8d��e]I��T9��RG��RG��U֙X1��]�\
d��e]I��]I��RG��X1��X1��]�\
]I��f�hg��h��Rh��Rkq�k���m/�1u?�&���倐�����L��L���*����������c��q��l��gK�gK�f�hh��Rm/�1�����L��L������v��q��gK�gK�h��Rk��ݕ�L��z���gK�k���m/�1m/�1��Lz���v��gK�m/�1m/�1z���v��";
		-- Mekthorg the Wild
		[ 18677 ] = "r�ss�k�tth1tth1vh>y�mpy�mp|Iu�z�{}(�4��~O��Ŏ�Ŏ;�n����}I�*}\\�p{x�\rk=�zj�h���h���ie�Fm/��m/��qN�v���v�xrsTu2r�sr�stth1y�mp}(�4��Ń���}c�?}I�*{x�\roO�ak=�zh���v�xrr�sy�mpz�~}(�4����}c�?{x�\rvܜ�oO�ah���m/��y���v�xry�mpz�~����������}c�?vܜ�r&��oO�am/��y���y�mpz�{���vܜ�r&��r&��m/��v���yX��y���z�{���r&��v���yX��z�{z�~���v���yX��z�~���yX���\"��L�u��٢�٣��R�����������U�ѯ.�ѯ.������J����p�y�\"��\"���٥��������ѯ.��J����\"�襻��������J�ݺ�����ݺ���";
		-- Vorakem Doomspeaker
		[ 18679 ] = "�F��C���G_��G���Ct��FE��FE��NO�xQ �xQ �[T���S���S���QG�sKƇsKƈF��G_�yI���G���FE��FE�xQ ��S���S��sKƍ�G_�yI���FE��S���G_�yI���S��a{��[r�\
f��\
f���]���[=��[=�b[��ub��ub��k���qh��qh�]y��2}V�2}V�a{��\
f��\
f���[=�ub��ub���qh�2}V�\
f��ub��2}V�Ș����D�r�·r�¼�¿H���H���!�̼��'���'�	��Ș��Ș��r�¿H���H�����'�Ș�b-Pvc�L�h_K~h_K~o�M�o�V�jkS�jkXRh�Y�h�Y�ctVfb-Pvh_K~o�V�jkS�jkS�h�Y�b-Pvh_K~jkS�b-Pv";
	};
	[ 491 ] = { -- Howling Fjord
		-- King Ping
		[ 32398 ] = "O!�(ST��PA�PA�M/��O!�(Ff�F���Ca�fCa�f>�S>I��Ca�f>I��Ff�M̽5N���P�P�P\r��M̽5QN�\000S,�R��R��Q��QN�\000Q�ϝSaɬW��W��W��jS�яW��S�яQ�ϝ";
		-- Perobas the Bloodthirster
		[ 32377 ] = "���u	�D�D��/�)\"T�)\"T�K!���傈��߀����D�)\"T�)\"T��倷��3G��.ҝ�2[��2[�w9���:D��2[��:D��3G�C.��I'\
��%F�&���̸>��>���#��*�{+W�p0��C.��C.���%F�&��&��>���*�{+W�C.��&��&���*�{+W";
		-- Vigdis the War Maiden
		[ 32386 ] = "��~��!u���pĵ�n��xe��b{�vem�e?�{h��{h���s������������u���u�������<�g�=�����̓g�t��~���pĵ�n���b{�vem�vem�{h���������߽��u���<�g�=�̓g�t���pĵ�n���n��vem���������u���<���<�̓g�:�t��H�t��n���n��������������<�:�t��H��n����������:�t��H";
	};
	[ 492 ] = { -- Icecrown
		-- High Thane Jorfus
		[ 32501 ] = "��g���b���]p��]p��Zǵ\
\\/�W��;Oi��Po��Po�Z^��_.��_.��f�i��i��Aj��g���g���]p�\
\\/�W���Po��_.��_.�i���g���g��\
\\/�W��W���_.��g�|P�auL��tt��tt��v�ȭz��_z��_~���&��&��o�{|P�a|P�att��z��_z��_�&�|P�aN��P��PN��WE��ZQ�Q[~��[�^ٳ�_v�1_v�1]���Z��+SõsP���O��ZPA��M�uN��WE��[~��X��p[�_v�1Z��+Z��+SõsO��ZPA��N��PN��WE��X��p[�[�Z��+O��ZPA��PN��WE��WE��[�O��ZWE��O��ZPA��";
		-- Hildana Deathstealer
		[ 32495 ] = "Jq�HXu�HRd�L�TI�L�JJF�JJF�MA�Q�B ]�?\r]p<j_:�_:�`�<�`@\000`@\000^(D�UtI�M}N�P.S�N.]O` RdtS9ieS9ieR&n�L�uI�w�E�}OD�{�HXu�Jq�N�mVJ�fRJq�HRd�]B3]�?\r_:�LIJ�M}N�N.]S9ieL�uI�w�I�w�D�{�HXu�L�b�J�fRHRd�]B3_:�`@\000S9ieI�w�HXu�L�b�HRd�K)]�]B3`@\000UtI�S9ieHXu�N�mVO�h�L�b�K)]�U�F�]B3UtI�S9ieN�mVO�h�O�h�K)]�L�TQ�B U�F�UtI�O` S9ieO�h�Q�B UtI�P�E�N.]O` O�h�Q�B P�E�M�E�N.]O�h�L�TJJF�Q�B M�E�LIJ�N.]L�TJJF�M�E�LIJ�L�TJJF�LIJǆ\
�B��~�r���r�����҄2���������͖��ޚ6�R���������E��M���M���Оv���p�*�􇧍��\
�B�\
�B�r���҄2�����͖��ޙ����M�����p���1�*��\
�B������ޙ����������p���K���1�\
�B�҄2����������K�U�r���1�҄2�҄2������K�҄2���K�U�r";
		-- Putridus the Ancient
		[ 32487 ] = "����쭫�xv?�{P��w鮐w鮐rh��r׈Dr׈DwE{��f��f��kaĘ�ct�>s�����@�f�@�f�֩*�,���,�������xv?�w鮐r׈D�>s��@�f�,���,�����x���ev���v?�r׈D�>s��,�����ezv���r׈D�>s����e�\"����k�zr׈D�>s��\"���`y*��k�r׈D�f���ct�>s��`y*�xg΃�k�f���ct�`y*��h���h��xg΂f���h��f���ct";
	};
	[ 477 ] = { -- Nagrand
		-- Bro'Gaz the Clanless
		[ 18684 ] = "Q�;�U�9DW�>W�>XRE�VsQVsQT,XMYH1`�FzD�AA���A��6>���>���>�A�}�CTyE�]�G�W�RJ�Q�C�Q�;�Q�;�W�>VsQH1`�D�AA���A���>���A�}�RJ�Q�;�VsQA���A�}�CTyN�P�RJ�VsQH1`�A���CTyG�W�N�P�VsQH1`�CTyG�W�G�W�VsQMYI�\\�H1`�G�W�MYI�\\�G�W�n�Um\"�^t%��t%��t��Is3��uY��{\"��}5�熡�ہ���\r��\r��~�Z�3���*�݌6�[�~���ǋ��7�S��C���ą�z�|�f�|�f|��y{�by��t���n�Un�Ut%��s3�ņ���\r�܃3���3���*�݌~���ǋ���C���ą��Ā|�f{�bn�Us3��uY�����ۃ3���~������{�by��y��n�UuY���\
�ކ��ی~��y��uY��}5��\
�ތ~���ǋ�����y��}5��ϕ��\
�މǋ�����}5��N��ϕ��ǋ����āN��ϕ����Ĕ��ٔ����f���f��������5���\\�Y���V�ϸǲ��n���ѳ��Ѷ��-����0���Ĕ��������˥������˄������F���F����y���y�����ٖf�����\\��V�ƿѵϸǳ��Ѷ���������%���˄���F�y���y���f�����5�ϸǶ���0��0�����%��Ծ˘�˄�y���ƿѵϸǸ0��Ծ˗y�����5�ƿѸ0��%��%��Ծ˝��5���\\�ƿѣ%����5���\\�%�";
		-- Goretooth
		[ 17144 ] = "��¼�������V���V����������¼���V���V��������A[�A<��<��?��/A؟;E��;E���RןbT�bT�\rX$�[J��Q:��O���Iy��Iy�kDЊCA���A[��<��?���?��;E��bT�bT�[J�7V��7V���Q:��Iy��Iy�CA���A[��A[��?��bT�bT�7V���Iy�bT��Iy��A[NwROHuYV�t�V�t�Y�pb]\"r]\"r_p�`vr�`vr�`�x�^(|^(|_˃9\\V��\\V��W��N��N\\�7MB��O.{dO.{dNwRV�t�V�t�]\"r`vr�^(|\\V��N��N��N\\�7O.{dO.{dV�t�`vr�`vr�^(|N��`vr�N��O.{dg$b�i=^�l�a�m�c�sh$r�j�r�j�t`o�tw�r�z~t�}It9�k�zxi�{gfw�gfw�e�ruh�irh�irj�lPh�qNk�h_j�lPh�irh�e�g$b�l�a�r�j�tw�r�z~r�z~t9�k�zxgfw�h�irh�qNk�h_h�irh�e�h�e�l�a�m�c�r�z~k�zxgfw�gfw�h�qNi^u�n;h*k�h_h�e�r�z~gfw�i^u�n;h*h�e�m�c�r�z~i^u�nvw�p�j�n;h*m�c�r�z~nvw�r-s�p�j�m�c�r�j�r�j�r�z~r-s�r�j�r-s�p�j�";
		-- Voidhunter Yar
		[ 18683 ] = "Z��z_�^V�]a���^V�]_�c��e��?g_��e�f㮸gղ�gղ�j���k��g�ygX��e��be��bc3ġ`H�_`H�_a�6^��}]���Y��U��ST�P'��Nv��R�OQ[��R�,R�,N��O���Sg��U��X�X�W8��Y۟�Z��z^V�]Z���a���_�c��c��g_��e�gղ�k��g�yg�ye��b`H�_`H�_^��}]���]���U��ST�ST�Nv��R�OR�,O���Sg��X�Y۟�Z��zZ��zZ���W��\000c���a���c��c��e�gղ�gղ�g�y`H�_`H�_]���ST�ST�R�OR�,R�,Sg��X�X�Z��zW��\000c���c��gղ�R�,X�W��\000b���c���gղ�R�,W��\000U��b���gղ�`H�_ST�R�,U��_��'b���`H�_ST�U��U��[���_��'`H�_ST�U��Wվ;Wվ;[���`H�_Wվ;`H�_ST�";
	};
	[ 479 ] = { -- Netherstorm
		-- Chief Engineer Lorthander
		[ 18697 ] = "@UlC�`�F^pF^pJ`�KPctKPctJf?G>g�G>g�D�npB�phB�ph@�o�@Ul@UlF^pKPctG>g�B�ph@UlKPctG>g�@Ult9�&tF��v���v���}�̑��H��H��_|6ۿ|6ۿw�ڟt9�&t9�&v�����H��H|6ۿt9�&�Y�����G��\\��\\�.�H�\\�ݟ\\�ݝ��q���������Y����\\��\\�\\�ݗ���";
		-- Ever-Core the Punisher
		[ 18698 ] = "<k]:�e>�c�I�jKd�S3j�S3j�O.p�J�uJ�uD�u@Nr�@Nr�<k]>�c�FRmI�jS3j�S3j�J�u@Nr�@Nr�>�c�?ph�FRmS3j�@Nr�@Nr�?ph�B ldB ldFRm@Nr�;6�:=��@!�SD��>Iy�nK��K��J)��G�gG�gJ���I��I��=���78�78�2G�o0|�*0|�*2T��4���4���7\
�\r6���>p�P;6�@!�SD��>K��G�g78�0|�*4���A�i>p�P@!�S@!�SD��>G�g78�4���6���A�i@!�SG�g78�6���9��B��sA�iG�g78�9��>V��A�<B��sG�gI��78�>V��A�<G�gI��I��>V��A�<�eU���O���M}�nPߦ�O��Qʪ�Qʬ�V�4ie�4ie� u��*|�*|��!~ٞ.s{�p�.s{�!~ٞ!~ٓ3{�boi�boi�d2�m\\q�eU���M}�UP�*|��.s{�%r��lٚp�!~ُboi�m\\q�eU��eU��UP�nP߰4ie�*|�%r��lٞ!~ُboi�eU��nPߪ�Qʰ4ie�%r멦m��lgs��lُboi�4ie��m��Je�e`'�lgs�boi��Qʰ4ie�Je�/Y��e`'�boi��QʪJe��Y�/Y��boi�eU���Qʧ�YVա�V՜/Y��eU���Qʡ�V՗eU�";
		-- Nuramoc
		[ 20932 ] = "T%N�R�G�U�@oW�<]X52Zk0�Zk0�\\�0�_�6�_�6�a A_BC�\\<N�]�R�\\�U�\\�U�W�Y�U`W�U`W�T%N�U�@oW�<]Zk0�_�6�_�6�_BC�\\6D�[6G�\\<N�\\�U�\\�U�U`W�U�@oU�@oW�<]_�6�_�6�\\6D�[6G�[6G�\\�U�U�@oU�@o_�6�[6G��z������˘��{�y�{�������������{���{�d��	����:��ӆ8��8��z���˘��{������{���{�	����:��:�8���ˊ�˘��{���{��˰��{��:;^�:��r<�ƚJx��O�Ʈe���o.��mI��pv��pv��r��:vȺ�vȺ�t��>s��=nH�yd��Z��vN���I�t@4�{@4�{;^�<�ƚJx��e���l���o.��pv��vȺ�vȺ�s��=nH�ynH�yZ��vN���@4�{<�ƚCʘl���o.��vȺ�nH�yN���@4�{@4�{CʘJx��l���vȺ�nH�ynH�y@4�{Jx��Jx��l���nH�y";
	};
	[ 473 ] = { -- Shadowmoon Valley
		-- Ambassador Jerrikar
		[ 18695 ] = "F\
��H�yKPyKPyO;~M�&M�&J��ZIK��IK��F\
��KPyKPyM�&IK��p�Pbq�K^uYAAuYAAwsAhy�D�y�D�w�Q�tgSatgSap�PbuYAAuYAAy�D�tgSa�]\\��W�0Yԙ0YԘ�_�f��f���d��_'�_'�]\\��0Yԙ0YԒf��_'y=��{���|~��|~��z��xe��xe��q��4qĬ�qĬ�y=��|~��|~��xe��qĬ��B�ղ�L���^���^�d���ڧ��ڧ������u�2�u�2�I���������B�ո��^���^�ڧ��u�2���^�u�2���";
		-- Collidus the Warp-Watcher
		[ 18694 ] = "��;���7l�x43�x43��4n�\"6f�\"6f�58�'H��'H���H�uJ	�uJ	��V��HW$��8K��;��x43�uJ	�HW$��LC�38e��8K�x43�'H��uJ	��LC��:r�38e�x43�'H���LC��L���:r�x43�\"6f�\"6f�'H���L��\"6f��L���:r]Vjq_�i�il�il�m�qAu���u���w�*u��u��o���l6}5a�u]�x1[�u�[�u�[�o�]Vjq]Vjqil�u���u���u��l6}5a�u[�u�]Vjq]Vjqu���l6}5g�x�a�u]Vjql6}5g�x�]Vjq����È�!�ˎ!�ˌ<��ఉ�ఉ����4�m�O�Y�v��,�����.�z��y��y����\
��g��g�}�ѝ��i�!�ˋఉ�4�m�P�=�O�Y�,���8�����.�y��y���g���i�!�ˏ4�m�ػ��P�=�,���u���8���y����i���!�ːػ������P�=�u����^�8�����i���ػ������u����^���i���i�����������u�����i";
		-- Kraator
		[ 18696 ] = "e�f�j�a o�cZo�cZoOnjmjme�i�e�f�o�cZjme�f�i��Ri���m}��m}��q��KrЪWrЪWo���i��Rm}��rЪWi��R�lq ��ru��yX��yX�*�ؖ+H�+H�%y*�lq ��yX�+H�lq p�rqv��v��x	 4w�(ew�(eq-%?p�v��w�(ep�L/m5O�k�T�rMT�rMS�vEQbyQbyN�v�LrGLrGL/m5T�rMT�rMQbyLrG";
	};
	[ 493 ] = { -- Sholazar Basin
		-- Aotona
		[ 32481 ] = "r{�l{���y#�k͒�i��d�>d�>c���j��j��iǃFl�4l�4p�r{�lr{�ly#�p��p��k͒�d�>j��l�4r{�lr{�lp��d�>r{�ld�>j�������\000�[���[���������������D���������������[���[�����������:��+���������˩*�:��2�����#�B�#�B�����&��#�B�&��2��u?��sg�0lฺlฺl���i���gK��e��Tf���f���k��pѫ<pѫ<s�u?��lฺi���gK��gK��f���pѫ<pѫ<u?��lฺlฺgK��pѫ<";
		-- King Krush
		[ 32485 ] = "FL��@.��>c��>c��>�zD�tD�tK�a�P�]�P�]�Q�TZ�IZ�I_�K=`O!X�UYT@hrP�qoK�w�Ovz0P�}\"N\\�O��MNҦ8NҦ8P���R��R��OO�I>�I>�I���G_�G_�A���>���>���A��\\E���FL��>c��D�tZ�I`O!X�UYX�UYP�qoMjs�K�w�P�}\"N\\�NҦ8R��I>�I>�G_�>���FL��D�tP�]�P�]�Z�IX�UYK�w�N\\�NҦ8NҦ8I>�>���P�]�X�UYMjs�NҦ8>���E���FL��P�]�Mjs�K�w�NҦ8E���FL��Mjs�K�w�FL��K�w�E���t�l<w$b�z�g���g��c,�XdM�XdM�k���w���w�{J{dy�{dy�v�r t�l<t�l<z�g�.i�.i���g�XdM�XdM��w�{dy�{dy�t�l<.i�.i��XdM{dy���D�9�Ӆт�j�@��̄�����{�q�����k�_�k�_�C�	��ͤ��ͤ�E����ڒ��ڒ��ڟ���x�����8��t֍�t֍�n�B��D�j�@��������{�q�k�_��ͤ��ͤ��ڒ���x���x�����t֍�t֍��D�т�j�@����O�}�O�}�{�q��ͤ��ͤ���x�t֍�t֍�т�Q�F�Q�F�j�@�O�}�O�}��ͤ�t֍�Q�F�O�}�t֍";
		-- Loque'nahak
		[ 32517 ] = "����֯N���;���;����k��k�ܻ�ɻ��ɻ�������������;��k��k�ɻ�����k�\r�߾.� �8� �8��ͤ�̸�̸���#�k�\r� �8�̸�k�\r����~H�z~;�~;��uɅ�L��L��8�΂���~;��L����A6S��3n��3n��3n�	6��	;��	;���?v�M?b�M?b�[;��A6S�A6S��3n�	;��	;��M?b�A6SX�MVX�JJ[�F�[�F�`\000R]�T�[�F�]�T�X�MVL���O��R��R��PU��K��AK��AIάwL���R��K��AL���3ײ37_�\\9谂9谂9��05ɺd5ɺd2޹�3ײ39谂5ɺd3ײ3";
	};
	[ 478 ] = { -- Terokkar Forest
		-- Crippler
		[ 18689 ] = "V���Cע�Gf�hGf�hN�9Y�|wY�|wf�zJs�As�A}B�\"������������������x�̞m/�~X���V���Gf�hGf�hY�|ws�As�A����������m/�~q �2^�LX���Gf�h���q �2s3�5f�^�LGf�h���s3�5sg�f�Gf�hs�As�A���sg�l]�Lf�s�As�Asg�q&�s�Aq&�l]�L]���`\r�\ret�pet�pj͟!m��m��k\"��e²e²`�b]���]���et�pm��m��e²]���";
		-- Doomsayer Jurim
		[ 18686 ] = "]VN�\\)G�^.G^.G_�N�^BT�]aA_\000h�^\\n�^\\n�[�n�\\qh�\\qh�Zra�[�T9]VN�^.G^BT�]aA^\\n�\\qh�\\qh�[�T9]VN�]VN�^BT�]aA]aA\\qh�]VN�b�>�b�;�f�<~y	A�}c>҂�=��191�03:�g/��g/���2��5��5��7;��S@�}�B@yDE2m�Emm�Emh�Cge�?Ue�?Ub�>�f�<~�191�g/��5��S@�}�B@m�Eme�?Uf�<~i�@���=��191�5�m�Eme�?Ui�@���=��5��S@�m�Emi�@�nVB@y	A���=��S@�m�EmnVB@y	A�y	A��S@�m�Em��St�/PA��R�XVf�Z^��_i��o.�~�ր�Yc{��b��]��]�+YQ��US��US��St��R��o.�ր��q[�Yc{��]��US��US��R�XVf��`���o.��q[�Yc{��US�XVf��`���q[�Yc{�Yc{�XVf��_i��_i��`��Yc{";
		-- Okrek
		[ 18685 ] = "K^k�O�fRR�lPR�lPN�uFL�o�R�lPL�o�K^k�|�-w}\"�~�!�~�!�)��4t��4t~�4�|�-w~�!��4t|�-w�t9�s7l�=��=���Fm�{=�=��{=�t9����/��-�*�-�*�&�P�������S�\
�������-�*������������";
	};
	[ 11 ] = { -- The Barrens
		-- Takk the Leaper
		[ 5842 ] = "���`h��U��U��ݞ������!��'Y��'Y��&f��̘������U�����'Y��̛�̘����U��U������";
	};
	[ 495 ] = { -- The Storm Peaks
		-- Dirkee
		[ 32500 ] = "g���hr��i��oi��oj���i0��b���d9��b-��b-��^\\�	]B�L]B�L^��a���fȆsg���i��oi��oi0��ez�#b �Ab���b-��b-��]B�La���fȆsi��oez�#b �Ab-��a���a���fȆsez�#cЌ~b �Aa���ez�#cЌ~a���ifh�c�m�aum�auoic�j�ij�ilwm�j6p\rj6p\rg�j�ififm�auj�iifj�ij6p\r�}}�vE��tg��tg��t���{q��{q��Ŭ5Ŭ5ū}}��tg��tg��{q�5�";
		-- Skoll
		[ 35189 ] = "uz��w��2w��Rw��Ru���t��yw��Rt��yuz��o��|q4�5s3��s3��r��To��|J���J)��K��K��LƂ:J���LƥSLӢnP\r��P\r��N쥵LƥSF\
�F��H��H��GE��F\
�";
		-- Time-lost Proto Drake
		[ 32491 ] = "S9[q[�S�b-Mcb-Mcn5G�nOM<c�R]XrU?_�U?_�R�aoLc�G8m�H�t�IX}\\IX}\\M�x�V\
q�V\
q�]PiKa[f�a[f�d�hyg�kxg�kxi�pNi�|\"}�v�yow�jJw�jJw�dZy	`vwsMnOM<n5G�n5G�wyGπ�J��JᅵN5��R@��R@�V�?ZQ{djWq�@z��@z���~���������~.�	x��h՗\
d9��a:�%a:�%^���\\��\\��]���_���_���`���a��7f���h��Uj���j���o4��sZ��sZ��wy��z��c|��ʀU�C}\"�!k��jW�Ci*�Fi*�Ffm��c�~5��}\"�!�U�C�U�C���N�G���G��~���}\"�]}\"�]x��FuF�YuF�Yet�1a�a�^���^\\��^\\��[�OUz�4Uz�4M��bN��xI��N��xM��bM��bF8�DDM¼DM¼C��dG���J���G�Dg�<Dg�<D3�BG�.^�n[�q�S,y�Ik��G�.D3�BE�u�C�nHCZf�CZf�Dta�F�^�b-McnOM<c�Rc�RU?_�Lc�g�kxi�|\"iԅF}�v�w�jJy	`vOO}wsMn5G�n5G���J��R@��R@�?ZQ|jca{djW�@z���������x��qĐ�h՗\
a:�%\\��\\��_���a��7e���f���j���sZ��z��c|���|���}\"�!yǤ�k��i*�Fc�{d��~5���U�C�U�C�G��}\"�]Uz�4N��xU��~I��M��bDM¼DM¼G���J���Dg�<G�.G���Ik��D3�BE�}�E�u�CZf�F�^�S9[qb-Mcc�Rc�RLc�H�d`�|}�v�y	`vOO}n5G���R@����qĐ�lP�SsZ��|���yǤ�k��c�au��{d��U�C}\"�]^\\��Uz�4U��~G���I��DM¼J���Dg�<G���N�~�Ik��E�}�E�}�E�u�F�^�S9[qc�RH�d`��Q�OO}��R@sZ��yǤ�v�wX��{d��}\"�]^\\��U��~ZDɟG���G���DM¼J���G���I��:L^!S9[qH�d`��T���Q���R@sZ��v�t���s���wX��}\"�]^\\��ZDɟ]�LK��G���DM¼J���I��:L��`F�^�L^!H�d`��X	��T���R@sZ��t���r�s���}\"�]uF�Ya�^\\��]�LK��DM¼J���J���L��`Pb�fF�^�H�d`Gg΂�X	��R@|jcaj���sZ��r�e���s���uF�Ya�]�L]ٻ�N��K��J���J���Pb�fVȤ�E�}�F�^�Gg�y	`v��X	|jcaj���r�m��.e���uF�Ya�a�]ٻ�]5��W+�PN��J���E�}�Gg�G8m�y	`v|jcaz�fYj���m��.k��ca�He���a�W+�PJ���VȤ�E�}�G8m�IX}\\y	`vz�fY{djWe���j���k��b��ca�Ha�Y���W+�PVȤ�N�~�E�}�IX}\\�|y	`v{djWe���k��au��a:��b��a�[��Y���VȤ�S,y�N�~�IX}\\�|{djW����dg�e���au��a:��a�]5��^�nS,y�IX}\\4�N�|����a��7dg�au��au��a:��]5��^�nIX}\\V\
q�|���4�N����\\��a��7au��au��]5��[��aNl�^�nV\
q�v���|��񂽂�\\��au��[��aNl�V\
q�a[f�v��炽��lP�S\\��[��VȤ�cZm�aNl�a[f�p|�jv���lP�S\\��VȤ�]��ve�pNcZm�a[f�m5�Cp|�jlP�Sh՗\
\\��]��ve�pNa[f�g�kxj���m5�ClP�Sh՗\
]��va4��fr�e�pNg�kxiԅFj���lP�SlP�Sh՗\
a4��fs��fr�g�kxlP�Sa4��e��`fs��g�kxiԅFiԅFlP�Se��`iԅFe��`fs��";
		-- Vyragosa
		[ 32630 ] = "S�\\[�T9b�Nb�Nn�Hen�M�dR�]pYU�`�U�`�S@bL~d@G�n(IXu%I�~\000I�~\000NIy�VzrhVzrh]�i�a�gfa�gfefih1lh1li�p�j|�~\000wXy�o�w�j�w�j�x	d�yxaw�M�n�M�n�Hen�Hew�Hr�[K��[K��$NوDR�DR䇆W���Z�{�j��q���{���{��,b�,�a�,�a~���xr�4iD��d��Ha���a���_i�m\\��y\\��y^\\�=`��`��a-��b��gf�Ci��kd�Ckd�Co��_sɕYsɕYw闚z��}\"�n�Ĭ�}���lV��jǬ�i���i���fܹdc���~��`}��ŀĬ�Ĭ���񁷶�����\000ɟ}��\000}��\000y7��u���u���e���a�Եa�Ե_\\�o^��q^��q[���U���U���N.�O!�JƧO!�N.�N.�F���D��`D��`Dg�H�BJ��kG���D֛�D֛�D���HR��_Hn�\\raS�zqIۅ+HR��D���E�v�Dn�C�gRC�gRD�b@Gf_\\b�Nn�M�dR�dR�U�`�L~d@h1lj|�jD��~\000wXw�j�yxa�P w�M�n�Hen�He�[K��DR�DR䆮Z�|�d{�j���{��,�a�,�axr�4r3��iD��a���\\��y\\��y`��b��f�&gf�Ckd�CsɕYz��}\"�n}\"�n}���z6�%lV��i���c���{�Ȍ~��`�Ĭ�Ĭ恷��}��\000U���O!�U��\"JƧN.�D��`D��`H�BJ��kD֛�HR��Hl�WIۅ+D���FR~�E�v�C�gRGf_\\S�\\b�NdR�dR�L~d@Ie�\r|�~\000wXyxa�P n�He�DR�,�ar3��l���sɕY}\"�nz6�%lV��c���a��n{�Ȍ�Ĭ�}��\000^��qU���U��\"H$�{JƧD��`J��kD֛�Hl�WOAIۅ+FR~�FR~�E�v�Gf_\\S�\\dR�Ie�R@�P �DR�sɕYz6�%w1�.w�ω{�Ȍ}��\000^��qU��\"Z��CH��H$�{D��`J��kHl�WJk��Lq^�S�\\Ie�gUL�R@�DR�sɕYw1�.uf��tg�{w�ω}��\000^��qZ��C]}��Kx�-H��D��`J��kJk��M�Gf_\\Lq^�Ie�@X��gUL�DR�sɕYuf��ru��tg�{}��\000u���a�Ե^��q]}��Kx�-D��`J��kJ��kM�PѦ\
Gf_\\IeG�hr�@X��DR�|�dkd�CsɕYru��fEѣtg�{u���a�Ե]}��^I��Ob��Kx�-J��kJ��kPѦ\
W8�%FR~�Gf_\\G�hryxa�@X�|�dkd�Cru��n��fEѣu���a�Եa�Ե^I��]��`W���Ob��J��kFR~�G�hrG�n(yxa|�d{jf�kd�Cn��lV��c���fEѣa�ԵW���J��kW8�%FR~�G�n(I�~\000yxa{jf�{�j�f�&kd�ClV��bu�vc���a�ԵZ#�5W���W8�%OAFR~�I�~\000�\r|�yxa{�j�f�&lV��a��na�Ǔbu�va�Ե\\\"��Z#�5W8�%S�zqOAI�~\000�\r|�{�j��,�adִ�f�&a��na�Ǔa�Ե]��`_Hn�S�zqI�~\000���\r|��,�ab��dִ�a��na��na�Ǔ]��`_Hn�I�~\000Vzrh}(�����,�a\\��yb��a��na��n]��`\\\"��a�m5_Hn�Vzrhw��}(���,�a\\��ya��n\\\"��a�m5Vzrha�gfw���,�al���\\��y\\\"��W8�%c�nHa�m5a�gfp�w��l���\\��yW8�%^O�f\
p�c�nHa�gfm���p�l���iD��\\��y^O�f\
p�a�gfh1lk)�Cm���l���iD��^O�a��wf�s�f\
p�h1ljD��k)�Cl���l���iD��a��wf�;f�s�h1ll���a��we��f�;h1ljD��jD��l���e��jD��e��f�;";
	};
	[ 201 ] = { -- Un'Goro Crater
		-- Ravasaur Matriarch
		[ 6581 ] = "�����ݚ��s��s�p�X�G���G���3�&�G���G�����f���m�ݴ���!�C��C��ο������²,����������s�G���G���G�����m�ϰ��ݴ��C��C������G�����m�_���ϰ��C�뛅�������G���_���_���ϰ�����";
	};
	[ 40 ] = { -- Wetlands
		-- Razormaw Matriarch
		[ 1140 ] = "��M��J)�|G��|G��?I��L���L���O�T��T��gXr�'X��;Tg�Pb��M��M�|G���L���L��T��'X��;Tg��M��L���L��'X��;Tg";
	};
	[ 467 ] = { -- Zangarmarsh
		-- Bog Lurker
		[ 18682 ] = "g$��e¥�e��oe��oh1�Qlw�9{����n���������_�����������Э�������������l�nk���j��Cj��Cg$��e��olw�9{����������������l�nj��Ce��o����������mV�Il�ne��o�������~\r�Ap\r��mV�Ie��o����~\r�AzǛp\r��e��olw�9lw�9����zǛlw�9zǛp\r�����Zσ�O�u���u��ד�M�ʦ�ʦ��֓�A�<�A�<���x���\\���\\֍��s�M���K���Z�u���u���ʦ�A�<�A�<���\\�s�M�s�M���K�u���u���A�<�s�M5�=�:74@�2�@�2�G�4�J=7�J=7�K^;K?�K?�HRGsDJ�DJ�<�M�8�M8�M:�E�?EF:A�:�E�8�M8�M4{EY5�=�@�2�J=7�K?�K?�DJ�8�M8�M?EFA�B�:A�8�M5�=�K?�8�MA�B�<�;~:A�5�=�K?�A�B�CM<j<�;~5�=�@�2�@�2�K?�CM<j@�:D<�;~@�2�@�2�CM<j@�:D";
		-- Coilfang Emissary
		[ 18681 ] = "AUy*=�ao>i]5>i]5A\\VDn_!Dn_!FLxE�{�E�{�CT|cAUy*AUy*>i]5Dn_!Dn_!E�{�AUy*��[��JX��{]��{]��Rb3�Qi7�Qi7�7p�9uɤ9uɠGt��j#��e�Wb�`��`��[��{]��{]��Qi7�9uɝ�e��`�{]��{]��9uɠj#�{]��j#��e�,���R�m�����������<���������t�'�{���{���,���������������{�����X�pŮ�;�;�G¯���*�;���*���X�רk������\\���\\�֠��`�l�`�l��٩�ݩ�ݦ��ȝҶ��Ҷ���m�Ү�רk���\\�`�l�`�l��ݝҶ��Ҷ��Ү�רk�רk�`�l�Ҷ���֮���h�������H����Q���Q�)����֮���콄�Q��֮�s�⴨Ů��M��M��È��K��M��K�s��";
		-- Marticar
		[ 18680 ] = "��)z��u8+�W�,�M�.M<.M<0�Q�0!\\/0!\\/.�`b-`�)m�,s3*	w1�� �������Q�������u8#�j+�W�.M<0!\\/)m�*	w1%?vY�� �������#�j(�_!(�_!+�W�0!\\/(�h�)m�%?vY!�yr�� ��(�_!0!\\/-`�(�h�%?vY!�yr!�yr��(�_!(�_!-`�(�h�(�_!(�h�!�yr]\"]�b[R�h$P\000s�P|y^K��K�K�HS��VY�VY�UYr��Zr\000Uru\\qi7]cecndMf�a�hDa�hD]�bM]\"]�]\"]�h$P\000n�Q�s�P|�K�VY�VY��Zr\000Uecna�hD]\"]�]\"]�n�Q�s�P|s�P|�VY\000Ui7]cecn]\"]�]\"]�s�P|\000U\000Ui7]c]\"]���t�'cF�h^�h^��Y���[=��[=�\\`|�\\d���o��I�����������\\�6��|��|�9����{���{���t�h^�h^滄[=�\\d���o�������|��|��{��h^�h^�\\d���o��h^���o���|";
	};
	[ 496 ] = { -- Zul'Drak
		-- Gondria
		[ 33776 ] = "����˟\r�����g���m��-t2�-t2�i���g���� ���[���I���I�p̞������I������ Õ�����ʟ��ʟ���r�y���������+�j�n���n���T��Õ��Õ��ʟ�����������n��Õ���2yk�g�n�}��}�� yx�2yk";
		-- Griegen
		[ 32471 ] = ")βM,��4{�(:J� E��G��%G��%G���B �B �B&�@;ʟ@;ʟ5�Ϊ1��w1��w1��X4��?<��-I�*^��*^��)βM4{�(:J� G��%B �1��w4��?7y�_<��*^��4{�(4{�(:J� B �@;ʟ1��w7y�_><��<��4{�(@;ʟ7y�_<���><��4{�(B �B �@;ʟ<���B �<���><��>Ҏ(A��lC׆�C׆�G���G��?'�6>w��;ԣ{;ԣ{62��5t��5t��7��k<6�>?.��>Ҏ(C׆�C׆�G��D֒�?'�6;ԣ{5t��?.��C׆�D֒�D֒�?'�65t��<6�>?.��D֒�D֒�5t��<6�>!u��!N��$�6$�6'���*���*���)e�#��	#��	!u��$�6$�6*���#��	";
		-- Terror Spinner
		[ 32475 ] = "��V�aQ-�!P��!P��Uփ�V�#bޘr]���Y>��Y>�\rWȠ�\\ڠ�\\ڝIeF�e��e��#bޙ�Y>��Y>��\\ڛe���6�3���6㺘6��;��@4��Cʹ�PA��Q���Q��mO}�?I�?���;)��6��6��6�@4��Cʵ�Q��?I�?���6�@4�@4��Cʴ?I�@4�?I�?�ͤQ:σO���U���U��Zr��b���b��._�ͤQ:��U���b�ͤQ:öc�ȌfȠsnȠsn��s���gȠsn��göcʸΦ�����������ö�8���b���b�Ư߸Φ���ѿ��b�Φ�";
		-- Zul'drak Sentinel
		[ 32447 ] = "/�ү1:�hI��I��I��L���L���L��jH��cI׭0��0/���/���/�үI��L���H��cI׭I׭/���I��I��L���I׭a���f��hǀAn��)sÌ�rʑuw8�\rz�i|��|��{/�Jx��oB�`�2���:�/�:�/g��e��e��e�Ti�8l��i�8e�Te�Ta��a���a���hǀAi��i��n��)rʑuw8�\r|��x��oB�`�:�/e��e��i�8i�Ll��e�Ta���a���i��rʑut���w8�\rx��e��i�LkӬo���l��a���a���rʑut���t���x��u�oB�`e��kӬo���a���t���oB�`kӬoH��t��o���t���u�oB�`oH��t��t���u�u�oH��t%��u�t%��t��";
	};
-- [Ebonhold] vanilla zone path data - generated by tools/generate_pathdata.js
	[ 1 ] = { -- Elwynn Forest
		-- Bhag'thera
		[ 2938 ] = string.char(81, 184, 214, 163, 81, 184, 214, 163, 81, 184, 214, 163);
		-- Princess
		[ 2940 ] = string.char(234, 209, 142, 130, 234, 209, 142, 130, 234, 209, 142, 130);
		-- Morgan the Collector
		[ 2942 ] = string.char(60, 202, 81, 184, 60, 202, 81, 184, 60, 202, 81, 184);
		-- Fedfennel
		[ 3670 ] = string.char(81, 56, 91, 79, 81, 56, 91, 79, 81, 56, 91, 79);
	};
	[ 21 ] = { -- Tirisfal Glades
		-- Ressan the Needler
		[ 1482 ] = string.char(163, 112, 143, 66, 163, 112, 143, 66, 163, 112, 143, 66);
		-- Deeb
		[ 1484 ] = string.char(40, 156, 224, 122, 40, 156, 224, 122, 40, 156, 224, 122);
		-- Sri'skulk
		[ 1485 ] = string.char(132, 171, 245, 104, 132, 171, 245, 104, 132, 171, 245, 104);
		-- Bayne
		[ 1481 ] = string.char(142, 130, 204, 140, 142, 130, 204, 140, 142, 130, 204, 140);
		-- Muad
		[ 1480 ] = string.char(20, 46, 163, 112, 20, 46, 163, 112, 20, 46, 163, 112);
	};
	[ 215 ] = { -- Mulgore
		-- The Rake
		[ 3248 ] = string.char(255, 127, 163, 112, 255, 127, 163, 112, 255, 127, 163, 112);
		-- Snagglespear
		[ 3244 ] = string.char(91, 143, 193, 181, 91, 143, 193, 181, 91, 143, 193, 181);
		-- Arnak Grimtotem
		[ 3246 ] = string.char(163, 112, 173, 199, 163, 112, 173, 199, 163, 112, 173, 199);
		-- Enforcer Emilgund
		[ 3252 ] = string.char(224, 122, 173, 71, 224, 122, 173, 71, 224, 122, 173, 71);
	};
	[ 33 ] = { -- Silverpine Forest
		-- Grimson the Pale
		[ 1765 ] = string.char(245, 104, 153, 89, 245, 104, 153, 89, 245, 104, 153, 89);
		-- Mirelow
		[ 1766 ] = string.char(204, 140, 40, 156, 204, 140, 40, 156, 204, 140, 40, 156);
		-- Sever
		[ 1768 ] = string.char(71, 97, 81, 184, 71, 97, 81, 184, 71, 97, 81, 184);
		-- Slavering Worg
		[ 1770 ] = string.char(183, 158, 224, 122, 183, 158, 224, 122, 183, 158, 224, 122);
	};
	[ 38 ] = { -- Loch Modan
		-- Ol' Sooty
		[ 1107 ] = string.char(163, 112, 30, 133, 163, 112, 30, 133, 163, 112, 30, 133);
		-- Chok'sul
		[ 1108 ] = string.char(40, 156, 71, 97, 40, 156, 71, 97, 40, 156, 71, 97);
		-- Ambassador Infernus
		[ 1110 ] = string.char(204, 140, 193, 181, 204, 140, 193, 181, 204, 140, 193, 181);
		-- Grizlak
		[ 1112 ] = string.char(122, 84, 163, 112, 122, 84, 163, 112, 122, 84, 163, 112);
	};
	[ 41 ] = { -- Westfall
		-- Vultros
		[ 3868 ] = string.char(60, 138, 71, 97, 60, 138, 71, 97, 60, 138, 71, 97);
		-- Lieutenant Fangore
		[ 2932 ] = string.char(71, 97, 40, 156, 71, 97, 40, 156, 71, 97, 40, 156);
		-- Brute
		[ 2934 ] = string.char(193, 181, 204, 140, 193, 181, 204, 140, 193, 181, 204, 140);
	};
	[ 44 ] = { -- Redridge Mountains
		-- Bellygrub
		[ 447 ] = string.char(71, 97, 122, 148, 71, 97, 122, 148, 71, 97, 122, 148);
		-- Tethis
		[ 448 ] = string.char(40, 156, 163, 112, 40, 156, 163, 112, 40, 156, 163, 112);
		-- Noxious Shredder
		[ 449 ] = string.char(30, 133, 193, 181, 30, 133, 193, 181, 30, 133, 193, 181);
	};
	[ 10 ] = { -- Duskwood
		-- Mor'Ladim
		[ 1975 ] = string.char(81, 184, 204, 140, 81, 184, 204, 140, 81, 184, 204, 140);
		-- The Lich
		[ 1980 ] = string.char(163, 112, 71, 97, 163, 112, 71, 97, 163, 112, 71, 97);
		-- Stitches
		[ 2970 ] = string.char(142, 130, 183, 158, 142, 130, 183, 158, 142, 130, 183, 158);
	};
	[ 45 ] = { -- Arathi Highlands
		-- Fozruk
		[ 1688 ] = string.char(204, 140, 163, 112, 204, 140, 163, 112, 204, 140, 163, 112);
		-- Bimble Longberry
		[ 1689 ] = string.char(71, 97, 40, 156, 71, 97, 40, 156, 71, 97, 40, 156);
		-- Kovork
		[ 1692 ] = string.char(245, 168, 30, 133, 245, 168, 30, 133, 245, 168, 30, 133);
		-- Zaricotl
		[ 1694 ] = string.char(163, 112, 122, 84, 163, 112, 122, 84, 163, 112, 122, 84);
	};
	[ 40 ] = { -- Wetlands
		-- Sarltooth
		[ 1188 ] = string.char(163, 112, 204, 140, 163, 112, 204, 140, 163, 112, 204, 140);
		-- Togrul
		[ 1189 ] = string.char(40, 156, 71, 97, 40, 156, 71, 97, 40, 156, 71, 97);
	};
	[ 1413 ] = { -- Teldrassil
		-- Blackmoss the Fetid
		[ 3271 ] = string.char(163, 112, 204, 140, 163, 112, 204, 140, 163, 112, 204, 140);
		-- Gobbler
		[ 3273 ] = string.char(40, 156, 71, 97, 40, 156, 71, 97, 40, 156, 71, 97);
		-- Oakenscowl
		[ 3274 ] = string.char(30, 133, 245, 168, 30, 133, 245, 168, 30, 133, 245, 168);
	};
	[ 148 ] = { -- Darkshore
		-- Lady Moongazer
		[ 2184 ] = string.char(163, 112, 163, 112, 163, 112, 163, 112, 163, 112, 163, 112);
		-- Moonstalker Sire
		[ 2572 ] = string.char(204, 140, 122, 84, 204, 140, 122, 84, 204, 140, 122, 84);
		-- Mist Creeper
		[ 2185 ] = string.char(71, 97, 40, 156, 71, 97, 40, 156, 71, 97, 40, 156);
		-- Soriid the Devourer
		[ 2187 ] = string.char(40, 156, 204, 140, 40, 156, 204, 140, 40, 156, 204, 140);
		-- Theryssia
		[ 2188 ] = string.char(142, 130, 81, 184, 142, 130, 81, 184, 142, 130, 81, 184);
	};
	[ 15 ] = { -- Ashenvale
		-- Kreldig Ungor
		[ 12717 ] = string.char(163, 112, 204, 140, 163, 112, 204, 140, 163, 112, 204, 140);
		-- Kizrak
		[ 12718 ] = string.char(40, 156, 163, 112, 40, 156, 163, 112, 40, 156, 163, 112);
		-- Simone the Inconspicuous
		[ 5340 ] = string.char(204, 140, 71, 97, 204, 140, 71, 97, 204, 140, 71, 97);
	};
	[ 7 ] = { -- Stonetalon Mountains
		-- Brother Ravenoak
		[ 5915 ] = string.char(163, 112, 163, 112, 163, 112, 163, 112, 163, 112, 163, 112);
		-- Besseleth
		[ 5929 ] = string.char(204, 140, 40, 156, 204, 140, 40, 156, 204, 140, 40, 156);
		-- Karang Amakkar
		[ 5928 ] = string.char(71, 97, 204, 140, 71, 97, 204, 140, 71, 97, 204, 140);
	};
	[ 405 ] = { -- Desolace
		-- Gibblewilt
		[ 5354 ] = string.char(163, 112, 204, 140, 163, 112, 204, 140, 163, 112, 204, 140);
		-- The Minstrel
		[ 5355 ] = string.char(40, 156, 71, 97, 40, 156, 71, 97, 40, 156, 71, 97);
	};
	[ 357 ] = { -- Feralas
		-- Bloodroar the Stalker
		[ 5346 ] = string.char(71, 97, 204, 140, 71, 97, 204, 140, 71, 97, 204, 140);
		-- Diamond Head
		[ 5345 ] = string.char(40, 156, 163, 112, 40, 156, 163, 112, 40, 156, 163, 112);
		-- Brokespear
		[ 9662 ] = string.char(204, 140, 40, 156, 204, 140, 40, 156, 204, 140, 40, 156);
	};
};


